-- MySQL Script generated by MySQL Workbench
-- 03/05/17 01:08:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iwstats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iwstats` ;

-- -----------------------------------------------------
-- Schema iwstats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iwstats` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iwstats` ;

-- -----------------------------------------------------
-- Table `iwstats`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`players` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `steamId` VARCHAR(25) NOT NULL,
  `hash` CHAR(6) NULL,
  `state` TINYINT(2) UNSIGNED NULL DEFAULT 0,
  `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `steamId_UNIQUE` (`steamId` ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`messages` (
  `id` INT(10) UNSIGNED NOT NULL,
  `value` VARCHAR(128) NOT NULL,
  `TIMESTAMP(3)` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatList_players1_idx` (`playerId` ASC),
  CONSTRAINT `fk_chatList_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`nicknames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`nicknames` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nick` VARCHAR(32) NOT NULL,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nickNameList_players1_idx` (`playerId` ASC),
  CONSTRAINT `fk_nickNameList_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`weapons` (
  `weapon` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`weapon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`servers` (
  `hash` CHAR(6) NOT NULL,
  `address_ip` VARCHAR(15) NOT NULL,
  `address_port` CHAR(5) NOT NULL,
  PRIMARY KEY (`hash`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`maps` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`rounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`rounds` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `hash` CHAR(6) NOT NULL,
  `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endedAt` TIMESTAMP(3) NULL,
  `server` CHAR(6) NOT NULL,
  `mapId` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  INDEX `fk_rounds_servers1_idx` (`server` ASC),
  INDEX `fk_rounds_maps1_idx` (`mapId` ASC),
  CONSTRAINT `fk_rounds_servers1`
    FOREIGN KEY (`server`)
    REFERENCES `iwstats`.`servers` (`hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rounds_maps1`
    FOREIGN KEY (`mapId`)
    REFERENCES `iwstats`.`maps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`sessions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` CHAR(8) NULL,
  `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endedAt` TIMESTAMP(3) NULL,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  INDEX `fk_sessions_players1_idx` (`playerId` ASC),
  CONSTRAINT `fk_sessions_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`interactions` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `hash` CHAR(8) NOT NULL,
  `srcId` MEDIUMINT(8) UNSIGNED NOT NULL,
  `srcSessionId` INT(10) UNSIGNED NOT NULL,
  `destId` MEDIUMINT(8) UNSIGNED NOT NULL,
  `destSessionsId` INT(10) UNSIGNED NOT NULL,
  `weaponId` VARCHAR(10) NOT NULL,
  `roundId` MEDIUMINT(8) UNSIGNED NOT NULL,
  `damage` TINYINT(3) UNSIGNED NOT NULL,
  `rHealth` TINYINT(3) UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_interactions_players1_idx` (`srcId` ASC),
  INDEX `fk_interactions_players2_idx` (`destId` ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  INDEX `fk_interactions_weapons1_idx` (`weaponId` ASC),
  INDEX `fk_interactions_rounds1_idx` (`roundId` ASC),
  INDEX `fk_interactions_sessions1_idx` (`srcSessionId` ASC),
  INDEX `fk_interactions_sessions2_idx` (`destSessionsId` ASC),
  CONSTRAINT `fk_interactions_players1`
    FOREIGN KEY (`srcId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_players2`
    FOREIGN KEY (`destId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_weapons1`
    FOREIGN KEY (`weaponId`)
    REFERENCES `iwstats`.`weapons` (`weapon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_rounds1`
    FOREIGN KEY (`roundId`)
    REFERENCES `iwstats`.`rounds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_sessions1`
    FOREIGN KEY (`srcSessionId`)
    REFERENCES `iwstats`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_sessions2`
    FOREIGN KEY (`destSessionsId`)
    REFERENCES `iwstats`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`profiles` (
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  `nickName` VARCHAR(32) NOT NULL,
  `wins` MEDIUMINT(8) NULL DEFAULT 0,
  `losses` MEDIUMINT(8) NULL DEFAULT 0,
  `ratio` FLOAT(7,4) NULL DEFAULT 0,
  INDEX `ixWins` (`wins` DESC),
  INDEX `ixLosses` (`losses` DESC),
  INDEX `ixRatio` (`ratio` DESC),
  PRIMARY KEY (`playerId`),
  CONSTRAINT `fk_profiles_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `iwstats`.`maps`
-- -----------------------------------------------------
START TRANSACTION;
USE `iwstats`;
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_vertigo');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_train');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_sugarcane');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_stmarc');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_shorttrain');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_shortdust');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_safehouse');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_overpass');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_nuke');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_mirage');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_lake');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_inferno');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_dust2');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_dust');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_cbble');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_cache');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_bank');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'de_bank');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'cs_office');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'cs_militia');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'cs_italy');
INSERT INTO `iwstats`.`maps` (`id`, `name`) VALUES (DEFAULT, 'cs_assault');

COMMIT;

