-- MySQL Script generated by MySQL Workbench
-- 02/15/17 18:53:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iwstats
-- -----------------------------------------------------
drop database `iwstats`;
-- -----------------------------------------------------
-- Schema iwstats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iwstats` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iwstats` ;

-- -----------------------------------------------------
-- Table `iwstats`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`players` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `steamId` VARCHAR(25) NOT NULL,
  `hash` CHAR(6) NOT NULL,
  `state` TINYINT(2) UNSIGNED NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `steamId_UNIQUE` (`steamId` ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`ipList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`ipList` (
  `ip` VARCHAR(15) NOT NULL,
  `times` MEDIUMINT(8) UNSIGNED NULL DEFAULT 0,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`ip`),
  INDEX `fk_ipList_players1_idx` (`playerId` ASC),
  CONSTRAINT `fk_ipList_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`authList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`authList` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_authList_players_idx` (`playerId` ASC),
  INDEX `fk_authList_ipList1_idx` (`ip` ASC),
  CONSTRAINT `fk_authList_players`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authList_ipList1`
    FOREIGN KEY (`ip`)
    REFERENCES `iwstats`.`ipList` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`chatList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`chatList` (
  `id` INT(10) UNSIGNED NOT NULL,
  `value` VARCHAR(128) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatList_players1_idx` (`playerId` ASC),
  CONSTRAINT `fk_chatList_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`nickNameList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`nickNameList` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nick` VARCHAR(32) NOT NULL,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nickNameList_players1_idx` (`playerId` ASC),
  CONSTRAINT `fk_nickNameList_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`weapons` (
  `weapon` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`weapon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`servers` (
  `hash` CHAR(6) NOT NULL,
  `address_ip` VARCHAR(15) NOT NULL,
  `address_port` CHAR(5) NOT NULL,
  PRIMARY KEY (`hash`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`rounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`rounds` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `hash` CHAR(6) NOT NULL,
  `startedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `server` CHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  INDEX `fk_rounds_servers1_idx` (`server` ASC),
  CONSTRAINT `fk_rounds_servers1`
    FOREIGN KEY (`server`)
    REFERENCES `iwstats`.`servers` (`hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`interactions` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `hash` CHAR(8) NOT NULL,
  `src` MEDIUMINT(8) UNSIGNED NOT NULL,
  `dest` MEDIUMINT(8) UNSIGNED NOT NULL,
  `weapon` VARCHAR(10) NOT NULL,
  `round` MEDIUMINT(8) UNSIGNED NOT NULL,
  `damage` TINYINT(3) UNSIGNED NOT NULL,
  `rHealth` TINYINT(3) UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_interactions_players1_idx` (`src` ASC),
  INDEX `fk_interactions_players2_idx` (`dest` ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  INDEX `fk_interactions_weapons1_idx` (`weapon` ASC),
  INDEX `fk_interactions_rounds1_idx` (`round` ASC),
  CONSTRAINT `fk_interactions_players1`
    FOREIGN KEY (`src`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_players2`
    FOREIGN KEY (`dest`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_weapons1`
    FOREIGN KEY (`weapon`)
    REFERENCES `iwstats`.`weapons` (`weapon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactions_rounds1`
    FOREIGN KEY (`round`)
    REFERENCES `iwstats`.`rounds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwstats`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwstats`.`profiles` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `playerId` MEDIUMINT(8) UNSIGNED NOT NULL,
  `nickName` VARCHAR(32) NOT NULL,
  `wins` MEDIUMINT(8) NULL DEFAULT 0,
  `losses` MEDIUMINT(8) NULL DEFAULT 0,
  `ratio` FLOAT(7,4) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_profiles_players1_idx` (`playerId` ASC),
  INDEX `ixWins` (`wins` DESC),
  INDEX `ixLosses` (`losses` DESC),
  INDEX `ixRatio` (`ratio` DESC),
  CONSTRAINT `fk_profiles_players1`
    FOREIGN KEY (`playerId`)
    REFERENCES `iwstats`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
